avance_proyecto/logisticpr/core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    
]

avance_proyecto/logisticpr/home/urls.py
from django.urls import path
from home import views

app_name = "home"
urlpatterns = [
    #RUTAS PARA VEHICULOS
    path('', views.Base.as_view(), name="base"),
    path('vehiculo/',views.ListarVehiculo.as_view(), name= 'vehiculoindex'),
    path('new/vehiculo/',views.NewVehiculo.as_view(), name='new_vehiculo'),
    path('delete/vehiculo/<str:pk>/',views.DeleteVehiculo.as_view(), name='delete_vehiculo'),
    path('update/vehiculo/<str:pk>/',views.UpdateVehiculo.as_view(), name='update_vehiculo'),
    path('detail/vehiculo/<str:pk>/',views.DetailVehiculo.as_view(), name='detail_vehiculo'),

    #RUTAS PARA MODELOS
    path('modelovehiculo/',views.ListarModeloVehiculo.as_view(), name= 'modelovehiculoindex'),
    path('new/modelovehiculo/',views.NewModeloVehiculo.as_view(), name='new_modelovehiculo'),
    path('update/modelovehiculo/<str:pk>/',views.UpdateModeloVehiculo.as_view(), name='update_modelovehiculo'),
    path('delete/modelovehiculo/<str:pk>/',views.DeleteModeloVehiculo.as_view(), name='delete_modelovehiculo'),
    path('detail/modelovehiculo/<int:pk>/',views.DetailModeloVehiculo.as_view(), name='detail_modelovehiculo'),


    #RUTAS PARA MARCAS
    path('marcavehiculo/',views.ListarMarcaVehiculo.as_view(), name= 'marcavehiculoindex'),
    path('new/marcavehiculo/',views.NewMarcaVehiculo.as_view(), name='new_marcavehiculo'),
    path('delete/marcavehiculo/<int:pk>/',views.DeleteMarcaVehiculo.as_view(), name='delete_marcavehiculo'),
    path('update/marcavehiculo/<int:pk>/',views.UpdateMarcaVehiculo.as_view(), name='update_marcavehiculo'),
    path('detail/marcavehiculo/<int:pk>/',views.DetailMarcaVehiculo.as_view(), name='detail_marcavehiculo'),
    
]

avance_proyecto/logisticpr/logisticpr/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")),
    path('core/', include("core.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

avance_proyecto/logisticpr/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from datetime import time, timedelta
from django.dispatch import receiver

# Create your models here.

#MODEL ROL
class Rol(models.Model):
    num = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)

#MODEL USER
class Usuario(models.Model):
    num = models.AutoField(primary_key=True)
    nombrePila = models.CharField(max_length=255)
    apPaterno = models.CharField(max_length=255)
    apMaterno = models.CharField(max_length=255)
    numTel = models.CharField(max_length=20)
    correo = models.EmailField()
    contrasena = models.CharField(max_length=255)
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE)

def __str__(self):
  return f'{self.nombrePila} {self.apPaterno} {self.apMaterno} - {self.rol}'

 
#MODEL VEHICLE
class Vehiculo(models.Model):
    numSerie = models.CharField(max_length=30, primary_key=True)
    placas = models.CharField(max_length=255)
    kilometraje = models.IntegerField()
    fechaAdquisicion = models.DateField()
    usaDiesel = models.BooleanField()
    conductor = models.ForeignKey(Usuario, on_delete=models.CASCADE)

def __str__(self):
  return f'{self.numSerie}'


#MODELO MARCAVEHICULO
class MarcaVehiculo(models.Model):
    num = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)

def __str__(self):
  return f'{self.nombre}'


#MODELO MODELOVEHICULO
class ModeloVehiculo(models.Model):
    num = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=255)
    consumoCombustible = models.FloatField()
    cantCarga = models.IntegerField()
    capPasajeros = models.IntegerField()
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)

def __str__(self):
  return f'{self.nombre}'
 

#MODELO VEHICULOUSUARIO
class VehiculoUsuario(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    class Meta:
        unique_together = (("vehiculo", "usuario"),)

avance_proyecto/logisticpr/home/forms.py
from django import forms
from .models import  Usuario, Rol, VehiculoUsuario, Vehiculo, ModeloVehiculo, MarcaVehiculo
#PUT HERE THE FORMS

#//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#HERE ARE THE CLASSES FOR THE MODELS, HERE YOU CAN CREATE THE DIFFERNT CLASSES FOR UPDATE OR CRATE DIFFERENT MODELS
#CLASSES:

#USUARIO
class UpdateUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [

        ]

class NewUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = [

        ]

#ROL
class UpdateRolForm(forms.ModelForm):
    class Meta:
        model = Rol
        fields = [

        ]

class NewRolForm(forms.ModelForm):
    class Meta:
        model = Rol
        fields = [

        ]

#VEHICULOUSUARIO
class UpdateVehiculoUsuarioForm(forms.ModelForm):
    class Meta:
        model = VehiculoUsuario
        fields = [

        ]

class NewVehiculoUsuarioForm(forms.ModelForm):
    class Meta:
        model = VehiculoUsuario
        fields = [

        ]

#VEHICULO
class UpdateVehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = [
            "numSerie",
            "placas",
            "kilometraje",
            "fechaAdquisicion",
            "usaDiesel",
            "conductor"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'w-full p-2 border rounded-lg shadow-sm focus:outline-none focus:ring focus:border-blue-300',
                'style':'margin: .5rem 0;',
            })

class NewVehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = [
            "numSerie",
            "placas",
            "kilometraje",
            "fechaAdquisicion",
            "usaDiesel",
            "conductor"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'w-full p-2 border rounded-lg shadow-sm focus:outline-none focus:ring focus:border-blue-300',
                'style':'margin: .5rem 0;',
            })

#MODELOVEHICULO
class UpdateModeloVehiculoForm(forms.ModelForm):
    class Meta:
        model = ModeloVehiculo
        fields = [
            "num",
            "nombre",
            "consumoCombustible",
            "cantCarga",
            "capPasajeros",
            "vehiculo"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'w-full p-2 border rounded-lg shadow-sm focus:outline-none focus:ring focus:border-blue-300',
                'style':'margin: .5rem 0;',
            })

class NewModeloVehiculoForm(forms.ModelForm):
    class Meta:
        model = ModeloVehiculo
        fields = [
            "num",
            "nombre",
            "consumoCombustible",
            "cantCarga",
            "capPasajeros",
            "vehiculo"
        ]

#MARCAVEHICULO
class UpdateMarcaVehiculoForm(forms.ModelForm):
    class Meta:
        model = MarcaVehiculo
        fields = [
            "num",
            "nombre",
            "vehiculo"
        ]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'w-full p-2 border rounded-lg shadow-sm focus:outline-none focus:ring focus:border-blue-300',
                'style':'margin: .5rem 0;',
            })

class NewMarcaVehiculoForm(forms.ModelForm):
    class Meta:
        model = MarcaVehiculo
        fields = [
            "num",
            "nombre",
            "vehiculo"
        ]

avance_proyecto/logisticpr/home/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.views import generic
from django.views.generic import ListView
from django.urls import reverse_lazy
from .models import Usuario, Rol, Vehiculo, VehiculoUsuario, MarcaVehiculo, ModeloVehiculo
from .forms import UpdateUsuarioForm, NewUsuarioForm, UpdateRolForm, NewRolForm, UpdateVehiculoUsuarioForm, NewVehiculoUsuarioForm, UpdateVehiculoForm, NewVehiculoForm, UpdateModeloVehiculoForm, NewModeloVehiculoForm, UpdateMarcaVehiculoForm, NewMarcaVehiculoForm

# Create your views here.
# def index(request):
#   return render(request, "home/index.html", {})

#PLANTILLA RETORNO
class Base(generic.View):
    template_name="base/base.html"
    context= {}

    def get(self, request):
        return render(request, self.template_name, self.context)
    
#PLANTILLA PARA VEHICULO
#HOME/VEHICULO
class NewVehiculo(generic.CreateView):
    template_name = "home/new_vehiculo.html"
    model = Vehiculo
    form_class = NewVehiculoForm
    success_url = reverse_lazy("home:vehiculoindex")#Aqui es a donde quieras retornar cuando se delete


class ListarVehiculo(generic.View):
    template_name = "home/vehiculos.html"
    context = {}

    def get(self, request):
        self.context = {
            "vehiculo": Vehiculo.objects.all()
        }
        return render(request, self.template_name, self.context)
    
#PENDIENTE
class DetailVehiculo(generic.View):
    template_name = "home/detail_vehiculo.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "vehiculo": get_object_or_404(Vehiculo, numSerie=pk)
        }
        return render(request, self.template_name, self.context)


class DeleteVehiculo(generic.DeleteView):
    template_name = "home/delete_vehiculo.html"
    model = Vehiculo
    success_url = reverse_lazy("home:vehiculoindex")
    success_message = "Vehiculo was deleted successfully."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)



class UpdateVehiculo(generic.UpdateView):
    template_name = "home/update_vehiculo.html"
    model = Vehiculo
    form_class = UpdateVehiculoForm
    success_url = reverse_lazy("home:vehiculoindex")

    def get_object(self, queryset=None):
        return get_object_or_404(Vehiculo, numSerie=self.kwargs['pk'])
    

#PLANTILLA PARA MARCAVEHICULO
class NewMarcaVehiculo(generic.CreateView):
    template_name = "home/new_marcavehiculo.html"
    model = MarcaVehiculo
    form_class = NewMarcaVehiculoForm
    success_url = reverse_lazy("home:marcavehiculoindex")


class ListarMarcaVehiculo(generic.View):
    template_name = "home/marcavehiculos.html"
    context = {}

    def get(self, request):
        self.context = {
            "marcavehiculo": MarcaVehiculo.objects.all()
        }
        return render(request, self.template_name, self.context)


class DetailMarcaVehiculo(generic.View):
    template_name = "home/detail_marcavehiculo.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "marcavehiculo": get_object_or_404(MarcaVehiculo, num=pk)
        }
        return render(request, self.template_name, self.context)


class DeleteMarcaVehiculo(generic.DeleteView):
    template_name = "home/delete_marcavehiculo.html"
    model = MarcaVehiculo
    success_url = reverse_lazy("home:marcavehiculoindex")
    

class UpdateMarcaVehiculo(generic.UpdateView):
    template_name = "home/update_marcavehiculo.html"
    model = MarcaVehiculo
    form_class = UpdateMarcaVehiculoForm
    success_url = reverse_lazy("home:marcavehiculoindex")
    

#PLANTILLA PARA MODELOVEHICULO
class NewModeloVehiculo(generic.CreateView):
    template_name = "home/new_modelovehiculo.html"
    model = ModeloVehiculo
    form_class = NewModeloVehiculoForm
    success_url = reverse_lazy("home:modelovehiculoindex")


class ListarModeloVehiculo(generic.View):
    template_name = "home/modelovehiculos.html"
    context = {}

    def get(self, request):
        self.context = {
            "modelovehiculo": ModeloVehiculo.objects.all()
        }
        return render(request, self.template_name, self.context)


class DetailModeloVehiculo(generic.View):
    template_name = "home/detail_modelovehiculo.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "modelovehiculo": get_object_or_404(ModeloVehiculo, num=pk)
        }
        return render(request, self.template_name, self.context)


class DeleteModeloVehiculo(generic.DeleteView):
    template_name = "home/delete_modelovehiculo.html"
    model = ModeloVehiculo
    success_url = reverse_lazy("home:modelovehiculoindex")
    

class UpdateModeloVehiculo(generic.UpdateView):
    template_name = "home/update_modelovehiculo.html"
    model = ModeloVehiculo
    form_class = UpdateModeloVehiculoForm
    success_url = reverse_lazy("home:modelovehiculoindex")

avance_proyecto/logisticpr/templates/home/delete_marcavehiculo.html
{% extends 'base/base.html' %}

{% block title %}Delete Marca View{% endblock title %}

{% block content %}
<div class="px-4 md:px-10 mx-auto w-full -m-24">
  <div class="flex flex-wrap mt-4">
    <div class="w-full mb-12 px-4">
      <div
        class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-white"
      >
        <div class="rounded-t mb-0 px-4 py-3 border-0">
          <form action="" method="post" >
            {% csrf_token %}
            <h1 class="text-red-500 text-center text-xl" style="margin: 1rem 0;">Advertencia</h2>
            <p class="text-center px-2 py-5">¿Realmente deseas eliminar la marca numero {{ object.num }} llamada "{{object.nombre}}"?</p>
            <div class="w-full flex justify-center items-center" style="margin: 2rem 0 ;">
              <div class="rounded-xl p-4 bg-emerald-500 ">
                <a href="{% url 'home:vehiculoindex' %}" class=" text-white ">Cancel</a>
                
              </div>
              <div class="rounded-xl p-4 bg-red-500" style="margin: 0 2rem;">
                <button type="submit" class="text-white">Eliminar</a></button>
              </div>
            </div>
            {% csrf_token %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

avance_proyecto/logisticpr/templates/home/delete_modelovehiculo.html
{% extends 'base/base.html' %}

{% block title %}Delete Modelo View{% endblock title %}

{% block content %}
<div class="px-4 md:px-10 mx-auto w-full -m-24">
  <div class="flex flex-wrap mt-4">
    <div class="w-full mb-12 px-4">
      <div
        class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-white"
      >
        <div class="rounded-t mb-0 px-4 py-3 border-0">
          
          <form action="" method="post" >
            {% csrf_token %}
            <h1 class="text-red-500 text-center text-xl" style="margin: 1rem 0;">Advertencia</h2>
            <p class="text-center px-2 py-5">¿Realmente deseas eliminar el modelo con numero {{ object.num }} llamado "{{object.nombre}}"?</p>
            <div class="w-full flex justify-center items-center" style="margin: 2rem 0 ;">
              <div class="rounded-xl p-4 bg-emerald-500 ">
                <a href="{% url 'home:modelovehiculoindex' %}" class=" text-white ">Cancel</a>
              </div>
              <div class="rounded-xl p-4 bg-red-500" style="margin: 0 2rem;">
                <button type="submit" class="text-white">Eliminar</a></button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

avance_proyecto/logisticpr/templates/home/marcavehiculos.html
{% extends 'base/base.html' %} 
{% block title %}Marcas{% endblock title %}
{%block header%}

<div class="relative bg-emerald-500 md:pt-32 pb-32 pt-12">

  <div class="px-4 md:px-10 mx-auto w-full ">
    <div>
      <!-- Card stats -->
      <div class="flex flex-wrap">
        <div class="w-full lg:w-6/12 xl:w-3/12 px-4">
          <div
            class="relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg"
          >
            <div class="flex-auto p-4">
              <div class="flex flex-wrap">
                <div class="relative w-full pr-4 max-w-full flex-grow flex-1">
                  <h5 class="text-blueGray-400 uppercase font-bold text-xs">
                    Traffic
                  </h5>
                  <span class="font-semibold text-xl text-blueGray-700">
                    350,897
                  </span>
                </div>
                <div class="relative w-auto pl-4 flex-initial">
                  <div
                    class="text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-red-500"
                  >
                    <i class="far fa-chart-bar"></i>
                  </div>
                </div>
              </div>
              <p class="text-sm text-blueGray-400 mt-4">
                <span class="text-emerald-500 mr-2">
                  <i class="fas fa-arrow-up"></i> 3.48%
                </span>
                <span class="whitespace-nowrap"> Since last month </span>
              </p>
            </div>
          </div>
        </div>
        <div class="w-full lg:w-6/12 xl:w-3/12 px-4">
          <div
            class="relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg"
          >
            <div class="flex-auto p-4">
              <div class="flex flex-wrap">
                <div class="relative w-full pr-4 max-w-full flex-grow flex-1">
                  <h5 class="text-blueGray-400 uppercase font-bold text-xs">
                    New users
                  </h5>
                  <span class="font-semibold text-xl text-blueGray-700">
                    2,356
                  </span>
                </div>
                <div class="relative w-auto pl-4 flex-initial">
                  <div
                    class="text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-orange-500"
                  >
                    <i class="fas fa-chart-pie"></i>
                  </div>
                </div>
              </div>
              <p class="text-sm text-blueGray-400 mt-4">
                <span class="text-red-500 mr-2">
                  <i class="fas fa-arrow-down"></i> 3.48%
                </span>
                <span class="whitespace-nowrap"> Since last week </span>
              </p>
            </div>
          </div>
        </div>
        <div class="w-full lg:w-6/12 xl:w-3/12 px-4">
          <div
            class="relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg"
          >
            <div class="flex-auto p-4">
              <div class="flex flex-wrap">
                <div class="relative w-full pr-4 max-w-full flex-grow flex-1">
                  <h5 class="text-blueGray-400 uppercase font-bold text-xs">
                    Sales
                  </h5>
                  <span class="font-semibold text-xl text-blueGray-700">
                    924
                  </span>
                </div>
                <div class="relative w-auto pl-4 flex-initial">
                  <div
                    class="text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-pink-500"
                  >
                    <i class="fas fa-users"></i>
                  </div>
                </div>
              </div>
              <p class="text-sm text-blueGray-400 mt-4">
                <span class="text-orange-500 mr-2">
                  <i class="fas fa-arrow-down"></i> 1.10%
                </span>
                <span class="whitespace-nowrap"> Since yesterday </span>
              </p>
            </div>
          </div>
        </div>
        <div class="w-full lg:w-6/12 xl:w-3/12 px-4">
          <div
            class="relative flex flex-col min-w-0 break-words bg-white rounded mb-6 xl:mb-0 shadow-lg"
          >
            <div class="flex-auto p-4">
              <div class="flex flex-wrap">
                <div class="relative w-full pr-4 max-w-full flex-grow flex-1">
                  <h5 class="text-blueGray-400 uppercase font-bold text-xs">
                    Performance
                  </h5>
                  <span class="font-semibold text-xl text-blueGray-700">
                    49,65%
                  </span>
                </div>
                <div class="relative w-auto pl-4 flex-initial">
                  <div
                    class="text-white p-3 text-center inline-flex items-center justify-center w-12 h-12 shadow-lg rounded-full bg-lightBlue-500"
                  >
                    <i class="fas fa-percent"></i>
                  </div>
                </div>
              </div>
              <p class="text-sm text-blueGray-400 mt-4">
                <span class="text-emerald-500 mr-2">
                  <i class="fas fa-arrow-up"></i> 12%
                </span>
                <span class="whitespace-nowrap"> Since last month </span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock header%}
{%block content%}
<div class="px-4 md:px-10 mx-auto w-full -m-24">
  <div class="flex flex-wrap mt-4">
    <div class="w-full mb-12 px-4">
      <div
        class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-white"
      >
        <div class="rounded-t mb-0 px-4 py-3 border-0">
          <div class="flex flex-wrap items-center">
            <div
              class="relative w-full px-4 max-w-full flex-grow flex-1"
            >
              <h3 class="font-semibold text-lg text-blueGray-700">
                Marcas
              </h3>
            </div>
          </div>
        </div>
        <!--table-->
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
          <table class="w-full text-sm text-left text-gray-500 ">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                  <tr>
                      <th scope="col" class="px-6 py-3">
                          Marca
                      </th>
                      <th scope="col" class="px-6 py-3">
                          Automovil
                      </th>
                      <th scope="col" class="px-6 py-3">
                          Acciones
                    </th>
                  </tr>
              </thead>
              <tbody>
                {% for marcavehiculo in marcavehiculo %}
                  <tr class="bg-white border-b">
                      <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                        {{ marcavehiculo.nombre }}
                      </th>
                      <td class="px-6 py-4">
                        {{ marcavehiculo.vehiculo.numSerie }}
                      </td>
                      <td class="px-6 py-4">
                        <button type="button" class="focus:outline-none bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"><a href="{% url 'home:update_marcavehiculo' marcavehiculo.num %}">Editar</a></button>
                        <button type="button" class="focus:outline-none bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"><a href="{% url 'home:delete_marcavehiculo' marcavehiculo.num %}" >Eliminar</a></button>                 
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
        </div>
      </div>
        <div class="rounded-xl p-4 text-center hover:underline" style="margin: 0 2rem;">
          <a href="{% url 'home:new_marcavehiculo' %}">Agregar</a>
        </div>
    </div>
  </div>
</div>                
{%endblock content%}

avance_proyecto/logisticpr/templates/home/modelovehiculos.html
{% extends 'base/base.html' %} 
{% block title %}Modelos{% endblock title %}
{%block content%}
<div class="px-4 md:px-10 mx-auto w-full -m-24">
  <div class="flex flex-wrap mt-4">
    <div class="w-full mb-12 px-4">
      <div
        class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded bg-white"
      >
        <div class="rounded-t mb-0 px-4 py-3 border-0">
          <div class="flex flex-wrap items-center">
            <div
              class="relative w-full px-4 max-w-full flex-grow flex-1"
            >
              <h3 class="font-semibold text-lg text-blueGray-700">
                Modelos
              </h3>
            </div>
          </div>
        </div>
        <!--table-->
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
          <table class="w-full text-sm text-left text-gray-500 ">
              <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                  <tr>
                    
                      <th scope="col" class="px-6 py-3">
                          Modelo
                      </th>
                      <th scope="col" class="px-6 py-3">
                          Automovil
                      </th>
                      <th scope="col" class="px-6 py-3">
                          Acciones
                    </th>
                    <th scope="col" class="px-6 py-3 invisible" style="opacity:0;">
                      Num
                    </th>  
                  </tr>
              </thead>
              <tbody>
                  {% for modelovehiculo in modelovehiculo %}
                  <tr class="bg-white border-b">
                      <td scope="row" class=" px-6 py-4 font-medium text-gray-900 whitespace-nowrap" >
                          {{ modelovehiculo.nombre }}
                      </td>
                      <td class="px-6 py-4">
                          {{ modelovehiculo.vehiculo.numSerie }}
                      </td>
                      <td class="px-6 py-4">
                          <a href="{% url 'home:update_modelovehiculo' modelovehiculo.num %}" class=" ">Actualizar </a>
                          <a href="{% url 'home:delete_modelovehiculo' modelovehiculo.num %}" class="">Eliminar</a>
                      </td>
                      <td style="opacity:0;" class="invisible">{{ modelovehiculo.num }}</td>

                  </tr>
                  {% endfor %}

              </tbody>
          </table>
        </div>
      </div>
      <div class="rounded-xl p-4 text-center hover:underline" style="margin: 0 2rem;">
        <a href="{% url 'home:new_modelovehiculo' %}">Agregar</a>
      </div>
    </div>
  </div>
</div>                
{%endblock content%}